org: warleon
service: pizza-scraper

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  timeout: 30
  iam:
    role: arn:aws:iam::407603477016:role/LabRole

  environment:
    TABLE_NAME: ${self:service}-${sls:stage}-pizza-table
    BUCKET_NAME: ${self:service}-${sls:stage}-pizza-bucket
    USERS_TABLE: ${self:service}-${sls:stage}-users
    TOKENS_TABLE: ${self:service}-${sls:stage}-tokens

package:
  individualy: true
  include:
    - types.py

functions:
  seed-products:
    handler: seed/products.lambda_handler
    timeout: 120
    package:
      include:
        - seed/**
  seed-admin-user:
    handler: seed/user.lambda_handler
    timeout: 120
    package:
      include:
        - seed/**

resources:
  Resources:
    TablaPizzas:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: tenant
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    TokensTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TOKENS_TABLE}
        AttributeDefinitions:
          - AttributeName: tenant
            AttributeType: S
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: tenant
            KeyType: HASH
          - AttributeName: id
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
        TimeToLiveSpecification:
          AttributeName: expiresAt
          Enabled: true

    BucketPizzas:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
