org: warleon
service: pizza-scraper

provider:
  name: aws
  runtime: python3.13
  region: us-east-1
  timeout: 30
  iam:
    role: arn:aws:iam::407603477016:role/LabRole

  environment:
    TABLE_NAME: ${sls:stage}-pizza-table
    BUCKET_NAME: ${sls:stage}-pizza-bucket

functions:
  seeder:
    handler: seed/seeder.lambda_handler
    timeout: 120
    package:
      include:
        - seed/**

resources:
  Resources:
    TablaPizzas:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_NAME}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

    BucketPizzas:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET_NAME}
